### ISSUE TITLE
Lessons Learned

### ISSUE THREAD

**Issue by mosdevly** [wampas/project2#43]
Final team meeting to write about what we learned, what we did well, what we want to improve next time, etc. We can publish it to this project wiki and use it as talking points for our presentation wrap-up.

**Comment by vikashiscool** [comment]
Sounds like a great idea. How about after we present tomorrow morning/afternoon?

**Comment by themargaretlee** [comment]
Great idea! Our sprint retrospective :)

**Comment by mosdevly** [comment]
@vikashiscool I was thinking more of getting our ideas about it down today so that we can actually use that during our presentation :) It doens't have to be a neat essay, but just a list of our experiences as a team and as individuals during the project work.

**Comment by themargaretlee** [comment]
Leaving some of my thoughts here. Not sure where we compiling our feedback. Will add more throughout the day.  

What we did well: (1) Helping each other out when any of us needed it (2) Being open about our issues 

What we want to improve next time: (1) User experience & research (2) User GitHub Issues Tracker as our main source of what needs to be done - sprint log

**Comment by mosdevly** [comment]
- Great start.
- Great framework.
- Underestimated time to troubleshoot
- Felt unprepared for Git, wish had more class time.
- UX: Not able to really take advantage.
- Know when to move on from an issue.
