### ISSUE TITLE
 RuntimeError: @controller is nil: make sure you set it in your test's setup method.

### ISSUE THREAD

**Issue by vikashiscool** [wampas/project2#6]
1) #new returns 200
     Failure/Error: before { get :new }
     RuntimeError:
       @controller is nil: make sure you set it in your test's setup method.
     # /Users/Vikash/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:701:in `block in check_required_ivars'
     # /Users/Vikash/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:699:in`each'
     # /Users/Vikash/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:699:in `check_required_ivars'
     # /Users/Vikash/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:587:in`process'
     # /Users/Vikash/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:65:in `process'
     # /Users/Vikash/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:505:in`get'
     # ./spec/controllers/articles_controller_spec.rb:42:in `block (2 levels) in <top (required)>'

**Comment by mosdevly** [comment]
Aaaaand ...fixed :dango:
