### ISSUE TITLE
After commenting out "before { get :new }"

### ISSUE THREAD

**Issue by vikashiscool** [wampas/project2#8]
Failures:

  1) #new renders articles/new
     Failure/Error: expect(response).to render_template 'articles/new'
       expecting <"articles/new"> but rendering with <[]>
     # ./spec/controllers/articles_controller_spec.rb:49:in `block (2 levels) in <top (required)>'

Finished in 0.06508 seconds (files took 3.36 seconds to load)
6 examples, 1 failure

**Comment by mosdevly** [comment]
Fixed :dancers:
